services:
  - type: web
    name: backend-new-kishan
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 5000
      - key: GMAIL_USER
        sync: false
      - key: GMAIL_APP_PASSWORD
        sync: false
      - key: RECIPIENT_EMAIL
        sync: false
      - key: FRONTEND_URL
        sync: false
